# Assignment 1: Numpy

Perform the follwing tasks:


In [1]:
#3.1: import the numpy library
import numpy as np

In [2]:
#3.2: create a random 10x10 array named A
A = np.random.rand(10,10)
A

array([[0.60441244, 0.31623048, 0.22208841, 0.7643091 , 0.66679294,
        0.22793839, 0.56848914, 0.73068125, 0.169497  , 0.75747827],
       [0.81498125, 0.05909981, 0.95463273, 0.06213985, 0.35424962,
        0.13274199, 0.22620041, 0.68952238, 0.81522726, 0.95693578],
       [0.98733167, 0.1735498 , 0.50686246, 0.80072845, 0.0261258 ,
        0.5112759 , 0.14429405, 0.08143659, 0.19362367, 0.4150388 ],
       [0.54973724, 0.70076937, 0.71299431, 0.15417304, 0.30968132,
        0.48130595, 0.10289358, 0.60208203, 0.63413433, 0.49780418],
       [0.21575008, 0.09049918, 0.59711986, 0.1285494 , 0.15736713,
        0.01620962, 0.8759062 , 0.23869341, 0.420679  , 0.4797731 ],
       [0.60771468, 0.09913674, 0.07129453, 0.14755634, 0.95359326,
        0.43042545, 0.48615905, 0.87494974, 0.81186759, 0.69233977],
       [0.38640749, 0.24705089, 0.1968028 , 0.85276717, 0.92893668,
        0.99344459, 0.77314611, 0.06837124, 0.75364314, 0.34887261],
       [0.32907977, 0.61204409, 0.9942665

In [3]:
#3.3: return only the odd rows of A
mask_rows = [(x % 2 != 0) for x in range(10)]
A[mask_rows,:]

array([[0.81498125, 0.05909981, 0.95463273, 0.06213985, 0.35424962,
        0.13274199, 0.22620041, 0.68952238, 0.81522726, 0.95693578],
       [0.54973724, 0.70076937, 0.71299431, 0.15417304, 0.30968132,
        0.48130595, 0.10289358, 0.60208203, 0.63413433, 0.49780418],
       [0.60771468, 0.09913674, 0.07129453, 0.14755634, 0.95359326,
        0.43042545, 0.48615905, 0.87494974, 0.81186759, 0.69233977],
       [0.32907977, 0.61204409, 0.99426651, 0.11552344, 0.55276002,
        0.37950701, 0.36207073, 0.11573146, 0.50282675, 0.58684439],
       [0.12674445, 0.77929146, 0.56303476, 0.64469306, 0.0727218 ,
        0.74850742, 0.65088371, 0.86788752, 0.91941031, 0.66333921]])

In [4]:
#3.4: perform a matrix multiplication of A with it's transposed
np.dot(A, A.T)

array([[3.05495407, 2.5326992 , 1.9989048 , 2.12924136, 1.60558508,
        2.8389594 , 2.73449885, 1.97678386, 2.28691586, 2.82240565],
       [2.5326992 , 3.83291476, 2.06946552, 2.78501669, 1.98187372,
        3.01095791, 2.20159659, 2.64008548, 2.66210635, 2.98198229],
       [1.9989048 , 2.06946552, 2.40230459, 1.79667287, 1.07311703,
        1.60243716, 2.14701549, 1.63865615, 1.70939098, 2.06451123],
       [2.12924136, 2.78501669, 1.79667287, 2.6760021 , 1.42356046,
        2.41591042, 2.19546449, 2.40829244, 2.71903716, 3.00215017],
       [1.60558508, 1.98187372, 1.07311703, 1.42356046, 1.68418171,
        1.66704331, 1.67309515, 1.66591829, 1.34915655, 2.02282258],
       [2.8389594 , 3.01095791, 1.60243716, 2.41591042, 1.66704331,
        3.64095817, 3.00170127, 2.13085996, 2.53767217, 2.96256089],
       [2.73449885, 2.20159659, 2.14701549, 2.19546449, 1.67309515,
        3.00170127, 4.11826321, 2.33458434, 2.48384659, 3.20012906],
       [1.97678386, 2.64008548, 1.6386561

In [5]:
#3.5: compute the matrix inverse of A
np.linalg.inv(A)

array([[-0.1055348 , -0.40073568,  0.57647068,  1.76057453,  0.77043133,
         0.20908957,  0.02466467, -0.89852184, -0.24910457, -0.88981167],
       [ 0.9253319 , -0.15425206, -1.10973713,  2.93048422,  0.07221188,
        -1.31081089,  0.67974059, -0.79034228, -0.69888258, -0.43725924],
       [ 0.02672618,  0.53201622, -0.2092449 ,  0.08896433,  0.49278624,
        -0.86404974,  0.27220175, -0.06547091,  0.64652641, -0.49951534],
       [ 2.15985246,  2.49920574, -2.49802777,  3.26921865, -0.16379592,
        -4.14434164,  2.9484801 , -3.26244113, -0.29075173, -1.08108378],
       [ 0.96727758,  0.68484978, -1.38112916,  1.39381464, -0.13039407,
        -1.07376064,  1.27114372, -0.66604544,  0.0633301 , -1.16076806],
       [-3.07201337, -3.489579  ,  4.50489067, -6.8284035 , -0.82782856,
         5.81474304, -3.96282502,  5.16201673,  0.97444022,  2.55467873],
       [-0.57008973, -1.46599302,  0.92647721, -0.73140108,  1.44360841,
         1.32866631, -0.84511945,  0.58308649

In [6]:
#3.6: divide all entries of A which are lager than 0.5 by 2 (hint: use where() )
mask = A > 0.5
A[np.where(mask)] / 2

array([0.30220622, 0.38215455, 0.33339647, 0.28424457, 0.36534063,
       0.37873913, 0.40749063, 0.47731637, 0.34476119, 0.40761363,
       0.47846789, 0.49366583, 0.25343123, 0.40036423, 0.25563795,
       0.27486862, 0.35038469, 0.35649716, 0.30104101, 0.31706716,
       0.29855993, 0.4379531 , 0.30385734, 0.47679663, 0.43747487,
       0.40593379, 0.34616988, 0.42638358, 0.46446834, 0.4967223 ,
       0.38657306, 0.37682157, 0.30602204, 0.49713326, 0.27638001,
       0.25141338, 0.29342219, 0.26080219, 0.45545795, 0.26115681,
       0.37097585, 0.49338714, 0.25295297, 0.38964573, 0.28151738,
       0.32234653, 0.37425371, 0.32544186, 0.43394376, 0.45970515,
       0.3316696 ])

In [7]:
A[np.where(mask)]

array([0.60441244, 0.7643091 , 0.66679294, 0.56848914, 0.73068125,
       0.75747827, 0.81498125, 0.95463273, 0.68952238, 0.81522726,
       0.95693578, 0.98733167, 0.50686246, 0.80072845, 0.5112759 ,
       0.54973724, 0.70076937, 0.71299431, 0.60208203, 0.63413433,
       0.59711986, 0.8759062 , 0.60771468, 0.95359326, 0.87494974,
       0.81186759, 0.69233977, 0.85276717, 0.92893668, 0.99344459,
       0.77314611, 0.75364314, 0.61204409, 0.99426651, 0.55276002,
       0.50282675, 0.58684439, 0.52160438, 0.9109159 , 0.52231362,
       0.7419517 , 0.98677428, 0.50590594, 0.77929146, 0.56303476,
       0.64469306, 0.74850742, 0.65088371, 0.86788752, 0.91941031,
       0.66333921])